version: '3'

services:
  aplikacija:
    build:
      context: .
      dockerfile: Dockerfile_app
    ports:
      - "8080:80" 
    depends_on:
      - baza_podatkov

  baza_podatkov:
    build:
      context: .
      dockerfile: Dockerfile_db